# Generated by Django 5.0.4 on 2024-07-07 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de rol')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de rol')),
                ('nombreRol', models.CharField(max_length=30, verbose_name='nombre del rol')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre del producto')),
                ('descripcion', models.CharField(max_length=700, verbose_name='descripcion producto')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(upload_to='foto producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_footprints.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False, verbose_name='id del carrito')),
                ('cantidad', models.IntegerField(verbose_name='cantidad del producto')),
                ('precio_total', models.IntegerField(verbose_name='total del carrito')),
                ('user_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_footprints.producto')),
            ],
        ),
    ]
