# Generated by Django 5.0.4 on 2024-04-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de rol')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de rol')),
                ('nombreRol', models.CharField(max_length=30, verbose_name='nombre del rol')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre del producto')),
                ('descripcion', models.CharField(max_length=700, verbose_name='descripcion producto')),
                ('precio', models.IntegerField(verbose_name='precio producto')),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(upload_to='foto producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_footprints.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre del usuario')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='correo usuario')),
                ('clave', models.CharField(max_length=12, verbose_name='clave usuario')),
                ('telefono', models.IntegerField(verbose_name='telefono usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_footprints.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de direccion')),
                ('calle', models.CharField(max_length=100, verbose_name='nombre calle')),
                ('numero', models.IntegerField(verbose_name='numero casa')),
                ('descripcion', models.CharField(max_length=600, verbose_name='descripcion direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_footprints.usuario')),
            ],
        ),
    ]
